config/routes.rb
Voice::Application.routes.draw do

resources :examinations do
	collection do
		get 'exam_choice'
		get 'list'

	end
	get 'instructions', :on => :member
	resources :chapters do
		get 'list', :on => :collection
	end
	end

	resources :chapters_examinations
	resources :chapters do
          collection do
            get 'list'
            get 'edit'

	  end
          resources :items do
	    collection do
	     get 'list'
	     get 'show_chapter'
	     post 'item_asx'

	    end
	 end
	end

   
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :fetch_chapter_id ,:only => [:index]
  before_action :admin?, :only => [:new, :edit, :create, :update, :destroy, :list]

  
  
  def index
  #?  @chapters=@examination.chapters.find(:all, :order =>'ind')
	
   #4 @ind=ChaptersExamination.find_by_chapter_id_and_examination_id(
   #4                                         params[:chapter_id],
   #4                                         params[:examination_id]).ind    
   
	
	

   @ind=ChaptersExamination.where(chapter_id: params[:chapter_id],
                                  examination_id: params[:examination_id]).first.ind
 
	 logger.info("lang=#{session[:lang]}")
	
    #4 @chapter_items = @chapter.items.find(:all,
    #4        :conditions =>[ "examination_id is NULL or examination_id = ?" ,params[:examination_id]],
    #4        :order=> 'ind')   
    
	 @chapter_items = @chapter.items.where("examination_id is NULL or examination_id = ?" ,params[:examination_id]).order(:ind)


     end

  
  def items_asx
     #Item.find(:all, :conditions => "number > -1")
    chapter= Chapter.find(params[:chapter_id].to_i)    
    @items = chapter.items.non_instructions 
    
    @items.each do | item|
      
      if item.kernel?   #kernel      
        @filename=item.text  
        @parts_number = item.parts_number              
        logger.info("PARTS NUMBER=={#@parts_number} for {#@filename}")
        asx_str = render_to_string :action=>"kernel_asx", :layout => false  
		
		 
      elsif item.question?  #question 
        @filename=item.question
        asx_str = render_to_string :action=>"question_asx", :layout => false  
		
		  
      end
      
      #logger.info("*** #{@filename}: #{asx_str}")      
      
      item.write_to_asx_file(@filename, asx_str)             
      
    end
    render :text => "Finished creating play lists"
  end  

    def list
     @chapter=Chapter.find(params[:chapter_id].to_i)
     @chapter_items= @chapter.items
	 render layout: 'list'

   end

   
   # GET /items/new
  def new
    @chapter=Chapter.find(params[:chapter_id])
    @item = Item.new
    @item.chapter=@chapter
    @item.ind=@chapter.items.count+1
    
  end

  # GET /items/1/edit
  def edit
    @chapter=Chapter.find(params[:chapter_id].to_i)
    @item = Item.find(params[:id])
  end

  # POST /examinations
  def create
    @item = Item.new
      if @item.create_by_params(params)
     	flash[:notice] = 'Item was successfully created.'
        redirect_to(list_chapter_items_url) 
       else
         render :action => "new" 
      end
  end

  # PUT /items/1
   def update
     @item=Item.find(params[:id])
  
      if @item.save_params(params[:item],params[:chapter_id])
        flash[:notice] = 'Item was successfully updated.'
        redirect_to(list_chapter_items_url) 
      else
        render :action => "edit" 
      end
  end

  # DELETE /items/1
 def destroy
    
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to(list_chapter_items_url) 
    end
  
 



private

  def fetch_chapter_id  

    I18n.locale = session[:lang] 
    @examination = Examination.find(params[:examination_id])
    @chapter = @examination.chapters.find(params[:chapter_id])
   
  
  end

  def item_params
      params.require(:item).permit(:name, :age)
    end
  
end

app/helpers/items_helper.rb
module ItemsHelper
   
    def item_label(item,ins_label,kernel_label,quest_label,essay_label)
    str=''    
    if item.instructions?
      str=ins_label
    elsif item.essay?
      str=essay_label  
    elsif item.kernel?
      str=kernel_label
    elsif
      str=quest_label+item.number.to_s
    end
    
  return str
  end
  
  # use this player_for to draw immidiatelly all the objects.
  # it will be more heavy for the browser.
  def player_for_3(chapter, number,filename, title='stam', color='blue',tracker=false )
      str=''
    if filename and !filename.empty?
      name = "#{FILES_ROOT}/#{chapter}/#{filename}"
      file_url = "#{request.base_url}/voice_data/#{chapter}/#{filename}"
       logger.info("/n name of the question is #{name}")
     if File.exist?( name)
      logger.info("/n id of the question is #{number}")
      label = title + '<br>'
      str +='<td style=" cursor: default; TEXT-ALIGN: center " ; bgcolor=' + color  + '> ' +label
      str +='<INPUT  TYPE="BUTTON" id="'+number+'_2" class="StopBtn"   onclick=Stop("'+number+'")>'
      str +='<INPUT  TYPE="BUTTON" id="'+number+'_1" class="PlayBtn"   onclick=PlayClick("'+number+'","'+file_url+'")>'
      if tracker==true
      end
      str +='</td>'
      end
    end

   return  str
  end

def show_row_player(chapter_number, item)
  
  title_all =  t('items.title_all');
  title_inst= t('items.title_inst');
  title_p =  t('items.paragraph');
  title_q =   t('items.question');
  title_e =   t('items.essay'); 
  
 
  if   item.number==-2
  #  logger.info(" item.number ==#{ item.number} item.ind==#{item.ind} item.question==#{item.question}")
    return player_for_3( chapter_number,item.ind.to_s, item.question+".ogg","", '#F9F085' )
  elsif   item.number==-1
  #  logger.info("item.ind==#{item.ind} item.instructions==#{item.instructions}")
    return player_for_3( chapter_number,item.ind.to_s, item.instructions+".ogg",title_inst, '#2AAAFF' )
  elsif item.number==0
     x= play_all(chapter_number,item.ind.to_s, item,title_all,'red') +
     player_for_3( chapter_number, item.ind.to_s+'_1',item.text+".1.ogg",title_p + " 1", '#7FFF7F',true ) +
     player_for_3( chapter_number,item.ind.to_s+'_2', item.text+".2.ogg",title_p + " 2", '#7FFF7F',true  ) +
     player_for_3( chapter_number,item.ind.to_s+'_3', item.text+".3.ogg",title_p + " 3", '#7FFF7F' ,true ) +
     player_for_3( chapter_number,item.ind.to_s+'_4',item.text+".4.ogg",title_p + " 4", '#7FFF7F' ,true ) +
     player_for_3( chapter_number,item.ind.to_s+'_5', item.text+".5.ogg",title_p + " 5", '#7FFF7F',true ) +
     player_for_3( chapter_number,item.ind.to_s+'_6', item.text+".6.ogg",title_p + " 6", '#7FFF7F',true )
   
     return x    
   
   elsif !item.question.blank?
   # logger.info("!!! #{chapter_number}, #{item.question}, #{title_q}")
     x=play_all(chapter_number, item.ind.to_s,item,title_all,'red')+
     player_for_3( chapter_number,item.ind.to_s+'_0', item.question+".0.ogg" ,title_q ,'#F9F085') +
     player_for_3( chapter_number,item.ind.to_s+'_1', item.question+".1.ogg", "1", '#ABD3C0' ) +
     player_for_3( chapter_number, item.ind.to_s+'_2',item.question+".2.ogg", "2", '#ABD3C0' ) +
     player_for_3( chapter_number, item.ind.to_s+'_3',item.question+".3.ogg", "3", '#ABD3C0' ) +
     player_for_3( chapter_number, item.ind.to_s+'_4',item.question+".4.ogg", "4", '#ABD3C0' ) 
     return x   
    end 
  
  end  


def check_max_paragraphs(cluster_name)
  
      name = cluster_name+".6.ogg";
      if File.exist?( name)
             max_index = 6;
             return max_index;
      end

      name = cluster_name+".5.ogg";
      if File.exist?( name)
             max_index = 5;
             return max_index;
      end
     
      name = cluster_name+".4.ogg";
      if File.exist?( name)
             max_index = 4;
             return max_index;
     else

       return 3 ;
     end
end
 
  
def  play_all(chapter, number,item ,title='stam', color='wheat' )
  if item.nil?
    return
  end

   if ( item.instructions)
     return
   end
   str=''
   if item.question and !item.question.empty?
      #file_url = "#{uri_root}/#{chapter}/asx/#{item.question}.asx"
      file_url = "#{uri_root}/#{chapter}/#{item.question}"
      label = title + '<br>'
      str +='<td style="cursor: default;" align=center ; bgcolor=' + color  + '> ' +label
      str +='<INPUT  TYPE="BUTTON" id="'+number+'_2" class="StopBtn"   onclick=ClusterStop("'+number+'")>'
      str +='<INPUT  TYPE="BUTTON" id="'+number+'_1" class="PlayBtn"   onclick=ClusterPlayClick("'+number+'","'+file_url+'")>'
      str +='</td>'

   elsif item.text and !item.text.empty?

     
      #file_url = "#{uri_root}/#{chapter}/asx/#{item.text}.asx"
      file_url = "#{uri_root}/#{chapter}/#{item.text}"
      file_name = "#{FILES_ROOT}/#{chapter}/#{item.text}"
      max_paragraphs = check_max_paragraphs(file_name); 
 

      label = title + '<br>'
      str +='<td style="cursor: default;" align=center; bgcolor=' + color  + '> ' +label
      str +='<INPUT  TYPE="BUTTON" id="'+number+'_2" class="StopBtn"   onclick=ClusterStop("'+number+'")>'
      str +='<INPUT  TYPE="BUTTON" id="'+number+'_1" class="PlayBtn"   onclick=ClusterPlayClick("'+number+'","'+file_url+'","'+max_paragraphs.to_s+'")>'
      str +='</td>'
    end


  end



 

 
 def draw_formulas_row(id,filename,title,color='wheat')
     s=''
     label = title
     name = "#{FORMULAS_ROOT}/#{filename}"
     file_uri = "#{uri_root}/formulas/#{filename}"
     #file_uri = "#{FORMULAS_URI}/#{filename}"
   if File.exist?( name)

          
      s +='<tr id="tr_'+id+'" style="cursor:default" onclick="toggle_visibility_formulas(\''+id+'\', 16)" >'
      s +='<td BGCOLOR="#ffdab9"  colspan=11 align=center >'
      s +='<h3>'+title+'</h3></td></tr>'
      s +='<tr style="display:none;" align="center" id="'+id+'">'
      s +='<td style="cursor: default;" align=center; bgcolor=' + color  + '> '+label +'<br>'
      s +='<INPUT  TYPE="BUTTON" id="'+id+'_2" class="StopBtn"   onclick=Stop("'+id+'")>'
      s +='<INPUT  TYPE="BUTTON" id="'+id+'_1" class="PlayBtn"   onclick=PlayClick("'+id+'","'+file_uri+'")>'
      s +='</td></tr>'

    end
    return s
  end

  
 #use this to define a table for formulas audio files in hebrew
def  heb_psycho_math(title,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16)
 
   str=''
   str +='<table  class="math_formulas_wide" id="math_formulas"   border=1 width=110>'
   str +='<th><h2>'+title+'</h2></th>'
   
   str += draw_formulas_row('f101','heb/psycho/math/nus_1fs.ogg',s1) 
   str += draw_formulas_row('f102','heb/psycho/math/nus_2ahuz.ogg',s2) 
   str += draw_formulas_row('f103','heb/psycho/math/nus_3hezka.ogg',s3) 
   str += draw_formulas_row('f104','heb/psycho/math/nus_4kefel.ogg',s4) 
   str += draw_formulas_row('f105','heb/psycho/math/nus_5dereh.ogg',s5) 
   str += draw_formulas_row('f106','heb/psycho/math/nus_6hespek.ogg',s6) 
   str += draw_formulas_row('f107','heb/psycho/math/nus_7meshulash.ogg',s7) 
   str += draw_formulas_row('f108','heb/psycho/math/nus_8malben.ogg',s8) 
   str += draw_formulas_row('f109','heb/psycho/math/nus_9trapez.ogg',s9) 
   str += draw_formulas_row('f110','heb/psycho/math/nus_10metsula.ogg',s10) 
   str += draw_formulas_row('f111','heb/psycho/math/nus_11igul.ogg',s11) 
   str += draw_formulas_row('f112','heb/psycho/math/nus_12teiva.ogg',s12) 
   str += draw_formulas_row('f113','heb/psycho/math/nus_13galil.ogg',s13) 
   str += draw_formulas_row('f114','heb/psycho/math/nus_14harut.ogg',s14) 
   str += draw_formulas_row('f115','heb/psycho/math/nus_15pir.ogg',s15)   
   str += draw_formulas_row('f116','heb/psycho/math/nus_16atseret.ogg',s16)   

 
  str +='</table>'
    
    return str    
end




 #use this to define a table for formulas audio files in arabic
def  arab_psycho_math(title,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16)
 
   str=''
   str +='<table class="math_formulas_wide arab_formulas" id="math_formulas"  border=1 width=200>'
   str +='<th><h2>'+title+'</h2></th>'
   
    str += draw_formulas_row('f101','arab/psycho/math/LAWS_01.ogg',s1) 
   str += draw_formulas_row('f102','arab/psycho/math/LAWS_PERCENT.ogg',s2) 
   str += draw_formulas_row('f103','arab/psycho/math/LAWS_HEZKA.ogg',s3) 
   str += draw_formulas_row('f104','arab/psycho/math/LAWS_KEFEL.ogg',s4) 
   str += draw_formulas_row('f105','arab/psycho/math/LAWS_DERECH.ogg',s5) 
   str += draw_formulas_row('f106','arab/psycho/math/LAWS_HESPEK.ogg',s6) 
   str += draw_formulas_row('f107','arab/psycho/math/LAWS_TRIANGLE.ogg',s7) 
   str += draw_formulas_row('f108','arab/psycho/math/LAWS_MALBEN.ogg',s8) 
   str += draw_formulas_row('f109','arab/psycho/math/LAWS_TRAPEZ.ogg',s9) 
   str += draw_formulas_row('f110','arab/psycho/math/LAWS_ZAVIYOT.ogg',s10) 
   str += draw_formulas_row('f111','arab/psycho/math/LAWS_CIRCLE.ogg',s11) 
   str += draw_formulas_row('f112','arab/psycho/math/LAWS_TEIVA.ogg',s12) 
   str += draw_formulas_row('f113','arab/psycho/math/LAWS_GALIL.ogg',s13) 
   str += draw_formulas_row('f114','arab/psycho/math/LAWS_HARUT.ogg',s14) 
   str += draw_formulas_row('f115','arab/psycho/math/LAWS_PIR.ogg',s15)     
   str += draw_formulas_row('f116','arab/psycho/math/LAWS_ATSERET.ogg',s16) 
 
  str +='</table>'
    
    return str    
end



end

app/views/items/_controls.html.erb

<div id="controls" >
<div id="rate">
 <h3><center> <%= t('controls.rate')-%><center></h3>

   <button name="button_rate" class="button_rate" disabled type="button"  onclick="ChangeRate(1.8)"><b><%= t('controls.very_fast')-%></b></button>&nbsp
   <button name="button_rate" class="button_rate" disabled type="button"  onclick="ChangeRate(1.4)"><b><%= t('controls.fast')-%></b></button>&nbsp    
   <button name="button_rate" style="border='solid'" type="button" onclick="ChangeRate(1.0)"><b><%= t('controls.normal')-%></b></button>&nbsp
 
 </div>


<div id="zoom">
 <h3><center> <%= t('controls.zoom')-%></center> </h3>
   <button name="button_zoom" class="button_zoom" type="button" onclick="ChangeZoom('scale(1)',this)"><b>300%</b></button>&nbsp    
   <button name="button_zoom" class="button_zoom" type="button" onclick="ChangeZoom('scale(1.5)',this)"><b>200%</b></button>&nbsp
   <button name="button_zoom" style="border='solid'" type="button" onclick="ChangeZoom('scale(2)',this)"><b>100%</b></button>&nbsp
  
 </div>

 
<%= link_to t('examinations.end_inst')  ,examinations_url, :class=>"link_to_exams" if examination.practice_exam?%>


</div>



app/views/items/_formulas_table.html - Copy (2).erb

  <%if @chapter.lang == "heb"%>
        <%= raw heb_psycho_math("השמעת נוסחאות","הגדרת 0 ו-1","אחוזים","חזקות","כפל מקוצר","בעיות דרך","בעיות הספק","משולש","שטח מלבן",
                    "שטח טרפז","זוויות פנימיות במצולע","עיגול, מעגל","תיבה, קובייה","גליל","נפח חרוט","נפח פירמידה","עצרת")%>
  <%else%>
        <%= raw arab_psycho_math(
"השמעת נוסחאות  إشارات وقوانين","הגדרת 0 ו-1 تعريف الصّفر والواحد","אחוזים النّسبة المئويّة","חזקות القوى","כפל מקוצר قوانين الضّرب المختصر","בעיות דרך مسائل في المسافة","בעיות  הספק مسائل في القدرة","משולש المثلّث","שטח מלבן مساحة مستطيل",
                    "שטח טרפז مساحة شبه منحرف","זוויות פנימיות במצולע مجموع الزوايا الداخليّة في مضلّع","עיגול, מעגל الدّائرة","תיבה, קובייה الصّندوق، المكعّب","גליל الأسطوانة","נפח חרוט حجم المخروط","פירמידה هرم","עצרת ددعلا بورضم")%>
 
<%end%>



app/views/items/_formulas_table.html - Copy.erb

  <%if @chapter.lang == "heb"%>
        <%= raw heb_psycho_math("השמעת נוסחאות","הגדרת 0 ו-1","אחוזים","חזקות","כפל מקוצר","בעיות דרך","בעיות הספק","משולש","שטח מלבן",
                    "שטח טרפז","זוויות פנימיות במצולע","עיגול, מעגל","תיבה, קובייה","גליל","נפח חרוט","נפח פירמידה")%>
  <%else%>
        <%= raw arab_psycho_math(
"השמעת נוסחאות  إشارات وقوانين","הגדרת 0 ו-1 تعريف الصّفر والواحد","אחוזים النّسبة المئويّة","חזקות القوى","כפל מקוצר قوانين الضّرب المختصر","בעיות דרך مسائل في المسافة","בעיות  הספק مسائل في القدرة","משולש المثلّث","שטח מלבן مساحة مستطيل",
                    "שטח טרפז مساحة شبه منحرف","זוויות פנימיות במצולע مجموع الزوايا الداخليّة في مضلّع","עיגול, מעגל الدّائرة","תיבה, קובייה الصّندوق، المكعّب","גליל الأسطوانة","נפח חרוט حجم المخروط","פירמידה هرم")%>
 
<%end%>



app/views/items/_formulas_table.html.erb

  <%if @chapter.lang == "heb"%>
        <%= raw heb_psycho_math("השמעת נוסחאות","הגדרת 0 ו-1","אחוזים","חזקות","כפל מקוצר","בעיות דרך","בעיות הספק","משולש","שטח מלבן",
                    "שטח טרפז","זוויות פנימיות במצולע","עיגול, מעגל","תיבה, קובייה","גליל","נפח חרוט","נפח פירמידה","עצרת")%>
  <%else%>
        <%= raw arab_psycho_math(
"השמעת נוסחאות  إشارات وقوانين","הגדרת 0 ו-1 تعريف الصّفر والواحد","אחוזים النّسبة المئويّة","חזקות القوى","כפל מקוצר قوانين الضّرب المختصر","בעיות דרך مسائل في المسافة","בעיות  הספק مسائل في القدرة","משולש المثلّث","שטח מלבן مساحة مستطيل",
                    "שטח טרפז مساحة شبه منحرف","זוויות פנימיות במצולע مجموع الزوايا الداخليّة في مضلّع","עיגול, מעגל الدّائرة","תיבה, קובייה الصّندوق، المكعّب","גליל الأسطوانة","נפח חרוט حجم المخروط","פירמידה هرم","עצרת مضروب العدد")%>
 
<%end%>



app/views/items/_item.html.erb
<tr style="display:none" align="center" id='<%=ind%>'  >
<% chapter_number=item.chapter.number %>


<%= raw show_row_player(chapter_number, item)%>


</tr>


app/views/items/_items_table.html.erb
<% if @chapter_items %>
  <table class="table_wide" id="table" width=500>
  <caption><%= render :partial => 'title' %></caption>
  <% @chapter_items.each_with_index do |item,ind| %>
    <tr id='tr_<%=ind%>' style="cursor:default"  onclick="toggle_visibility(<%=ind%>, <%=@chapter_items.size%>);"     >
    <td  class="<%= raw cycle('odd_row','even_row') %>" colspan=11 align=center    >
    <% if item.number > 0%>
       <h3  ><%= t('items.quest_number') %> <%=item.number%>
       </td>
       </tr>
    <% elsif item.number==0 %>
       <h3><%= t('items.kernel') %></td></tr>
     <% elsif item.number== -2 %>
       <h3><%= t('items.essay') %></td></tr>
    <% else %>
       <h3><%= t('items.instructions') %> <%= t(item.text) -%></td></tr>
    <% end %>
    </h3></tr>
    <%= render :partial => 'item', :locals => {:item => item, :ind => ind} %>
  <% end %>
  </table>
<%end%>
<br>

app/views/items/_title.html.erb
<div>
<h2> <%=@examination.name.html_safe%></h2>


<% if !@chapter %>
<h2><%= t('items.title') -%></h2>
<% else %>
      

 <% if @examination.chapters.first.name == 'essay' %> 
	   <table width=450 dir=rtl >
   <tr>
    <% @examination.chapters.each_with_index do|chapter,index|%>
  <td> <B>  
      <% if index == 0 %>
           <%= link_to t('items.essay'),chapter_items_url(chapter, :examination_id => @examination.id)  -%></B> </td>
	  <% else %>
    
  <%= link_to t('items.chapter')  +"  " +(index).to_s,chapter_items_url(chapter, :examination_id => @examination.id)  -%></B> </td>
     <% end %>
<% end %>
    <% else %>

  <table width=450 dir=rtl >
  <tr>
  <% @examination.chapters.each_with_index do|chapter,index|%>
  <td> <B>  
   
    
  <%= link_to t('items.chapter')  +"  " +(index+1).to_s,chapter_items_url(chapter, :examination_id => @examination.id)  -%></B> </td>
     
<% end %>
<% end %>
</tr>
</table>


 <% if @chapter.name == 'essay' %> 
     <p id="chapter_name_title"> <%= t('items.essay') -%> (<%=@chapter.number if hagahot?%>)

 <% else %>
   <p id="chapter_name_title"><%= t('items.chapter') -%> <%=@ind%> (<%=@chapter.name%> <%=@chapter.number if hagahot?%>)
<% end %>


</p>
<% end %>
</div>

app/views/items/create_asx.xml.erb
<ASX  Version="3.0">
 <entry>
     <Ref href="../"+<%=@filename%>+".0.ogg"/>
   </entry> 
<entry>
    <Ref href="../"+<%=@filename%>+".1.ogg"/>
   </entry> 
<entry>
    <Ref href="../"+<%=@filename%>+".2.ogg"/>
   </entry> 
<entry>
     <Ref href=".."+<%=@filename%>+".3.ogg"/>
   </entry> 
<entry>
    <Ref href="../"+<%=@filename%>+".4.ogg"/>
</asx> 

app/views/items/index.html.erb

<div id="container" >

<div id="sub_container">


<%if (@chapter.show_formulas == 1)%>
  <%= render :partial =>  'formulas_table' %>
<% end %>

<%= render :partial =>  'items_table' %> 

</div>
 

</div>

app/views/items/kernel_asx.html.erb
<ASX  Version="3.0">
 <% (1..@parts_number).each do |current_number| %>
 <entry>
      <Ref href="../<%=@filename%>.<%=current_number%>.ogg"/>
 </entry> 
  
 <%end%>
</asx> 

app/views/items/list.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Chapters: <%= controller.action_name %></title>
  <%= javascript_include_tag  "jquery.min", "jquery_ujs" %>
  <%= csrf_meta_tag %>
  <style>
    body {
      background-color: #cec9d0;
	}
  </style>
</head>
<body dir=rtl>
<p style="color: green "><%= flash[:notice] %></p>
<div dir=rtl>
<h2>רשימת פריטים בפרק <%= @chapter.number%></h2>
<table dir=rtl border=1 >


<th>כיתוב על המקש</th><th>שם הקובץ המושמע</th><th>אינדקס</th><th>רק עבור בחינה אחרת</th>
<% @chapter_items.each do |item| %>

<tr>
  

  <td><%=item_label(item, "הוראות","קטע קריאה","שאלה ","מטלת חיבור")%></td>
  <td dir=ltr><%=item.name%></td>

  
  <td><%=item.ind%> </td>
  <td><%=item.examination? %> </td>
 
  <td><%= link_to 'לערוך', edit_chapter_item_path(@chapter,item) %></td>
  <td><%= link_to 'למחוק', chapter_item_url(@chapter,item), data:{ confirm: 'Are you sure?' }, :method => :delete %></td>
   
 
 </tr>
<% end %>
 

</table>
<br>
<%= link_to 'פריט חדש', new_chapter_item_path(@chapter.id) %></br>
</br></br>
<hr>


<a href="/examinations/list">רשימת בחינות המוגדרות במערכת</a> </br> </br>
<a href="/chapters/list">רשימת הפרקים המוגדרים במערכת</a></br> </br>
<a href="/chapters_examinations">רשימת פרקים המשולבים בבחינות המוגדרים במערכת</a></br> </br>




</div>
</body>
</html>

app/views/items/new.html.erb

<div dir=rtl>

<script>
  var inst_name= '<%=@item.suggest_name(@item.chapter,-1)%>'
  var kernel_name='<%=@item.suggest_name(@item.chapter,0)%>'
  var quest_name= '<%=@item.suggest_name(@item.chapter,1)%>'
  var essay_name= '<%=@item.suggest_name(@item.chapter,-2)%>'
  function init(){
   
          document.getElementById("item_text").style.visibility="hidden";
     
     <%if @item.select_type <=0 %> 
	 document.getElementById("item_number").style.visibility="hidden";
     <%else%>
         document.getElementById("item_number").value='<%=@item.quest_number(@item.chapter)%>';
	 
     <%end%>


      document.getElementById("name").value = quest_name;
    
  }
</script>

<h1>הגדרת פריט חדש</h1>

 
 <%= form_tag(chapter_items_url , :method=> "post" ) do -%>
 
 <% if @item.errors.any? %>
  <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


  <p>
    מספר פרק<br />
    <%= @item.chapter.number %>
  </p>

   <p>
   סוג הפריט<br />
    <%= select("item","select_type",[["הוראות",-1],["קטע קריאה",0],["שאלה",1],["מטלת כתיבה",-2]],{ :include_blank => false} ,
                                                                             { :onchange => "suggestName(inst_name,kernel_name,quest_name,essay_name)" }) %>
  
   </p>
    <p>
     סוג הוראות-רק להוראות</br>
      <%=text_field(:item,:text,:size=>30) %>
    </p>
   <p>
     מספר סידורי - רק לשאלות</br>
      <%=text_field(:item,:number,:size=>3) %>
    </p>
   <p>
    אינדקס של הפריט-המקום הסידורי של הפריט בפרק </br>
     <input id="ind" name="ind" size="3" type="text" value=<%= @item.ind%> /> 
   </p>
   
   <p>
    שם פריט<br />
    <input dir ='ltr' id="name" name="name" size="10" type="text" value="" />
 
   </p>
  <p>
   משתתף רק בבחנה (לא חובה)<br />
   <%= select("item", "examination_id", Examination.find(:all).collect {|e| [ e.name ,e.id] }.uniq ,
                               { :include_blank => true }) %>
   </p>

  <p>
    <%= submit_tag 'לשמור'  %>
  </p>
<% end %>





<%= link_to 'Back', list_chapter_items_path(@item.chapter) %>
</div>

app/views/items/question_asx.html.erb
<ASX  Version="3.0">
 <% (0..4).each do |current_number| %>
 <entry>
     <Ref href="../<%=@filename%>.<%=current_number%>.ogg"/>
 </entry>
 
 <% end %>
</asx> 