config/routes.rb
Voice::Application.routes.draw do

resources :examinations do
	collection do
		get 'exam_choice'
		get 'list'

	end
	get 'instructions', :on => :member
	resources :chapters do
		get 'list', :on => :collection
	end
	end

	resources :chapters_examinations
	resources :chapters do
          collection do
            get 'list'
            get 'edit'

	  end
          resources :items do
	    collection do
	     get 'list'
	     get 'show_chapter'
	     post 'item_asx'

	    end
	 end
	end

   
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
 #4 has_many :items, :dependent => :destroy,:order=>'ind'
  #4 has_many :chapters_examinations, :dependent => :destroy
  #4 has_many :examinations, :through => :chapters_examinations

  has_many :items,->{ order(:ind) },:dependent => :destroy
  has_many :chapters_examinations, :dependent => :destroy
  has_many :examinations, :through => :chapters_examinations
 


   validates_uniqueness_of :number
   validates_presence_of  :number, :name, :lang
  #belongs_to :examination
 #4  attr_accessible :number, :name, :show_formulas, :lang


end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

 before_action :admin?, :only => [:new, :edit, :create, :update, :destroy, :list]

# GET /chapters
   def index
    @chapters = Chapter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @chapters }
    end
  end


 def edit
    @chapter = Chapter.find(params[:id])
  
  end
  
  
  # PUT /chapter/1
  def update
    @chapter = Chapter.find(params[:id])

      if @chapter.update_attributes(chapter_params)
        flash[:notice] = 'chapter was successfully updated.'
        redirect_to(list_chapters_url)
       else
       render :action => "edit" 
      end
   
  end
  
   #GET / chapter/new
   def new
       @chapter = Chapter.new
   end  
  
   # POST /chapters
  # POST /chapters.xml
  def create
    @chapter = Chapter.new(chapter_params)
     
     if @chapter.save   
      flash[:notice] = 'Chapter was successfully created.'
          redirect_to(list_chapters_url)         
      else
          render :action => "new" 
      end    
  end
  
  
  # DELETE /chapters/1
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    
      redirect_to(list_chapters_url) 
  
end
  
  #addition method for editing the chapters
  def list
     @chapter = Chapter.all.order('number') 
      render layout: false

  end

 def chapter_params
      params.require(:chapter).permit(:number, :name, :show_formulas, :lang)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_chapter.html.erb
<tr bgcolor=#fadefa>
	
<td align=center><%=player_for( item.question1 )%></td>
  	
<td align=center><%=player_for( item.question2 )%></td>
  

<td align=center><%=player_for( item.question3 )%></td>
  

<td align=center><%=player_for( item.question4 )%></td>  

<td align=center><%=player_for( item.question5 )%></td>

<td align=center><%=player_for( item.answer1 )%></td>

<td align=center><%=player_for( item.answer2 )%></td>

<td align=center><%=player_for( item.answer3 )%></td>

<td align=center><%=player_for( item.answer4 )%></td>

</tr>


app/views/chapters/edit.html.erb
<div dir=rtl>

<h1>עדכון פרק קיים</h1>

<%= form_tag(chapter_url , :method=> "put" ) do -%>
 
  <% if @chapter.errors.any? %>
  <ul>
    <% @chapter.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<table dir=rtl border=1%>
<tr><th>מספר פרק</th><th>שם פרק</th><th>שפת פרק</th><th>להציג נוסחאות</th> </tr> 

<tr>
  <td><%= text_field(:chapter,:number,:size=>10) %></td>
  <td><%= text_field(:chapter,:name) %></td>
  <td><%= select("chapter", "lang", Chapter.find(:all).collect {|e| [ e.lang ] }.uniq) %></td>
  <td><%= select("chapter", "show_formulas", Chapter.find(:all).collect {|e| [ e.show_formulas ] }.uniq, 
                         { :include_blank => false })
 %></td>
 </tr>

 

</table>
  <p>
      <%= submit_tag 'עדכן'  %>
  </p>
<% end %>


<%= link_to 'Back', list_chapters_path %>
</div>

app/views/chapters/index.html.erb
<body dir=rtl>
<center><h2>פרק מספר 10 הבנת הנקרא</h1>
<table dir=rtl WIDTH=100%>
  <tr>
<% for chapter in @chapters %>
<td><%= link_to "Chapter no " + chapter.number.to_s, {:action=>:index, :chapter_id=>chapter} %></td>
<% end %>
  </tr>
<% for item in @items %>
<tr><td BGCOLOR=#DEDEDE colspan=9 align=center><h3>שאלה מספר: <%=chapter.number%></td></tr>
<tr bgcolor=#ceface>
    
	<td>chapter</td>
	<td><%= link_to chapter.name, {:acition=>:show, :id=>chapter} %></td>
    <!--td><%= link_to 'Show', chapter %></td>
    <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
    <td><%= link_to 'Destroy', chapter, :confirm => 'Are you sure?', :method => :delete %></td-->

</tr>
<% end %>
</table>
<br>
<%= link_to 'New item', new_item_path %>




app/views/chapters/list.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Chapters: <%= controller.action_name %></title>
  <%= javascript_include_tag  "jquery.min", "jquery_ujs" %>
  <%= csrf_meta_tag %>
  <style>
    body {
      background-color: #cec9d0;
	}
  </style>
</head>
<body>
<p style="color: green "><%= flash[:notice] %></p>
<div dir=rtl  id="chapter_list">
<h2>רשימת הפרקים המוגדרים במערכת</h2></br>

<table dir=rtl border=1>

<tr><th>מספר פרק</th><th>שם פרק</th><th>שפת פרק</th> </tr>

<% @chapter.each do |chapter| %>
<tr>
  <td><%=chapter.number%></td>
  <td><%=chapter.name%></td>
  <td><%=chapter.lang%></td>
  <td><%= link_to 'לערוך', edit_chapter_path(chapter) %></td>
  <td><%= raw link_to 'למחוק', chapter, data: { confirm: "Are you sure?" }, :method => :delete %></td>
  <td><%= link_to 'רשימת פריטים', list_chapter_items_path(chapter) %></td>
  
 
 </tr>
<% end %>
 

</table>
<br>

<%= link_to 'פרק חדש', new_chapter_path %>


</br></br>
<hr>


<a href="/examinations/list">רשימת בחינות המוגדרות במערכת</a> </br> </br>
<a href="/chapters_examinations">רשימת פרקים המשולבים בבחינות המוגדרים במערכת</a></br> </br>

</div>

</body>
</html>

app/views/chapters/new.html.erb
<div dir=rtl>
<h1>הגדרת פרק חדש</h1>

 
 <%= form_tag(chapters_url , :method=> "post" ) do -%>
 
  <% if @chapter.errors.any? %>
  <ul>
    <% @chapter.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

  

  <p>
    מספר פרק<br />
    <%= text_field(:chapter,:number,:size => 10) %>
  </p>

   <p>
    שם פרק<br />
    <%= text_field(:chapter,:name) %>
   </p>

   <p>
    נוסחאות עבור הפרק<br />
    <%= select("chapter", "show_formulas",[["לא להציג",0],["להציג",1]], 
                                { :include_blank => false }) %>
   </p>

    <p>
    שפה<br />

    <%= select("chapter", "lang", Chapter.find(:all).collect {|e| [ e.lang ] }.uniq ,
                               { :include_blank => true }) %>
   </p>

  

  <p>
    <%= submit_tag 'לשמור'  %>
  </p>
<% end %>





<%= link_to 'Back', list_chapters_path %>
</div>

app/views/chapters/show.html.erb

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>