config/routes.rb
Voice::Application.routes.draw do

resources :examinations do
	collection do
		get 'exam_choice'
		get 'list'

	end
	get 'instructions', :on => :member
	resources :chapters do
		get 'list', :on => :collection
	end
	end

	resources :chapters_examinations
	resources :chapters do
          collection do
            get 'list'
            get 'edit'

	  end
          resources :items do
	    collection do
	     get 'list'
	     get 'show_chapter'
	     post 'item_asx'

	    end
	 end
	end

   
end

app/models/chapters_examination.rb
class ChaptersExamination < ActiveRecord::Base
  belongs_to :chapter
  belongs_to :examination

   validates_uniqueness_of :ind, :scope => [:examination_id]
   
   #4attr_accessible :examination_id, :ind
   def number
         chapter.number
   end

   

end

app/controllers/chapters_examinations_controller.rb
class ChaptersExaminationsController < ApplicationController

  before_action :admin?, :only => [:new, :edit, :create, :update, :destroy, :list, :index]

  # GET /chapters_examinations
  # GET /chapters_examinations.xml
  def index
    #@chapters_examinations = ChaptersExamination.find(:all,:order=>'examination_id,ind')
     @chapters_examinations = ChaptersExamination.all.order('examination_id').order(:ind)

       render layout: false

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.xml  { render :xml => @chapters_examinations }
     
	#end
     
  end

  # GET /chapters_examinations/1
  # GET /chapters_examinations/1.xml
  def show
    @chapters_examination = ChaptersExamination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chapters_examination }
    end
  end

  # GET /chapters_examinations/new
  # GET /chapters_examinations/new.xml
  def new
    @chapters_examination = ChaptersExamination.new
   
  end

  # GET /chapters_examinations/1/edit
  def edit
    @chapters_examination = ChaptersExamination.find(params[:id])
    @chapter=@chapters_examination.chapter
    @examination=@chapters_examination.examination
    ex = Examination.all
    @ce = ex.inject([]) {|mem, e| mem << e.chapters_examinations}.flatten!  
  end

  # POST /chapters_examinations
  def create
    chapter = Chapter.find(params[:chapter][:id])
    examination = Examination.find(params[:examination][:id])
    
    @chapters_examination = ChaptersExamination.new
    @chapters_examination.examination=examination
    @chapters_examination.chapter=chapter
    @chapters_examination.ind= params[:chapters_examinations][:ind]

      if @chapters_examination.save
        flash[:notice] = 'ChaptersExamination was successfully created.'
       redirect_to(chapters_examinations_url) 
       else
        render :action => "new" 
      end
  end

  # PUT /chapters_examinations/1
  def update
    @chapters_examination = ChaptersExamination.find(params[:id])
      #if @chapters_examination.update_attributes(params[:chapters_examination])
	  if @chapters_examination.update!(chapters_examination_params)
        flash[:notice] = 'ChaptersExamination was successfully updated.'
        redirect_to(chapters_examinations_url) 
      else
	   flash[:notice] = 'ChaptersExamination was successfully updated.'
       render :action => "edit" 
      end
  end

  # DELETE /chapters_examinations/1
  # DELETE /chapters_examinations/1.xml
  def destroy
    @chapters_examination = ChaptersExamination.find(params[:id])
    @chapters_examination.destroy

    respond_to do |format|
      format.html { redirect_to(chapters_examinations_url) }
      format.xml  { head :ok }
    end
  end
  
 #additional method for Ajax
 def show_ind
      indexes = ChaptersExamination.maximum(:ind,:group =>'examination_id')
      last_ind = indexes[params[:examination_id].to_i]
      @ind=(last_ind+1).to_s 
      render :partial => "ind_result",:layout=>false
      
   end   
    
   def chapters_examination_params
      params.require(:chapters_examination).permit(:examination_id, :ind, :chapter_id)
    end
  

end

app/helpers/chapters_examinations_helper.rb
module ChaptersExaminationsHelper
end

app/views/chapters_examinations/_ind_result.html.erb
 <input id="chapters_examinations_ind" name="chapters_examinations[ind]" size="3" type="text"  value="<%= @ind %>"/></div> 

  

app/views/chapters_examinations/edit.html.erb
<h1>עדכון פרק קיים</h1>

<%= form_tag(chapters_examination_url , :method=> "put" ) do -%>
 
  <% if @chapters_examination.errors.any? %>
  <ul>
    <% @chapters_examination.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>



 <p>
    משתתף בבחינה</br>
    <%= select("chapters_examination", "examination_id", Examination.all.collect {|e| [ e.name, e.id ] }, { :include_blank => true }  ) %>

   </p>

   <p>
    מספר סידורי בבחינה</br>
    <%=text_field(:chapters_examination,:ind,:size=>3) %> 
  
   </p>



  <p>
      <%= submit_tag 'עדכן'  %>
  </p>
<% end %>


<%= link_to 'Back', chapters_examinations_path %>

app/views/chapters_examinations/index.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Chapters: <%= controller.action_name %></title>
  <%= javascript_include_tag  "jquery.min", "jquery_ujs" %>
  <%= csrf_meta_tag %>
  <style>
    body {
      background-color: #cec9d0;
	}
  </style>
</head>
<body dir=rtl>
<p style="color: green "><%= flash[:notice] %></p>

<h2>רשימת הפרקים עבור הבחינות המוגדרים במערכת</h2>

<table border=1 dir=rtl>

  <% for chapters_examination in @chapters_examinations %>
<tr>
  <td><%=chapters_examination.chapter.name%> <%=chapters_examination.chapter.number%></td>
  <td><%=chapters_examination.examination.name%></td>
  <td><%=chapters_examination.ind%></td>
 
    <td><%= link_to 'לערוך', edit_chapters_examination_path(chapters_examination) %></td>
    <td><%= raw link_to 'למחוק', chapters_examination, data: { confirm: 'Are you sure?' }, :method => :delete %></td>
  </tr>
<% end %>
</table>

</br>

<%= link_to 'להגדיר שיבוץ חדש', new_chapters_examination_path %>
</br></br>

<hr>

<a href="/examinations/list">רשימת בחינות המוגדרות במערכת</a> </br> </br>
<a href="/chapters/list">רשימת הפרקים המוגדרים במערכת</a></br> </br>
</body>
</html>

app/views/chapters_examinations/new.html.erb
<h1>הגדרת שיבוץ חדש עבור פרק בבחינה</h1>

<%= form_for(@chapters_examination) do |f| %>
 <% if @chapters_examination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapters_examination.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @chapters_examination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  


 <p>
    הפרקים המוגדרים במערכת</br>
    <%= select("chapter", "id", Chapter.all.collect {|e| [ e.number, e.id ] }, { :include_blank => true }  ) %>

   </p>
   <p>
    המבחנים המוגדרים במערכת</br>
    <%= select("examination", "id", Examination.all.collect {|e| [ e.name, e.id ] }, { :include_blank => true }  ) %>

   </p>

   <p>
    מספר סידורי בבחינה</br>
   
   
  <div id="ind_result_div">  <%=text_field :chapters_examinations,:ind ,:size=>3 %></div> 
  <script>
   $("#examination_id").change(function(){$.get('/chapters_examinations/show_ind',{ examination_id: this.value}, function(html) { $("#ind_result_div").html(html); })});
   </script>
 	       
 
    
   
   </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', chapters_examinations_path %>

app/views/chapters_examinations/show.html.erb

<%= link_to 'Edit', edit_chapters_examination_path(@chapters_examination) %> |
<%= link_to 'Back', chapters_examinations_path %>