config/routes.rb
Voice::Application.routes.draw do

resources :examinations do
	collection do
		get 'exam_choice'
		get 'list'

	end
	get 'instructions', :on => :member
	resources :chapters do
		get 'list', :on => :collection
	end
	end

	resources :chapters_examinations
	resources :chapters do
          collection do
            get 'list'
            get 'edit'

	  end
          resources :items do
	    collection do
	     get 'list'
	     get 'show_chapter'
	     post 'item_asx'

	    end
	 end
	end

   
end

app/models/examination.rb
class Examination < ActiveRecord::Base
 #4 has_many :chapters_examinations, :order => 'ind', :include => 'chapter'
#4  has_many :chapters, :through => :chapters_examinations,  :order => 'chapters_examinations.ind'
   
 has_many :chapters_examinations, -> {includes( :chapter).order(:ind) }, :dependent => :destroy
 has_many :chapters, -> {order('chapters_examinations.ind')}, through: :chapters_examinations	
 

  has_many :items
  
   #attr_accessible  :name, :instruction, :lang, :exam_type
  validates_presence_of :exam_type, :name
  
def practice_exam?
  number==0
end  
  
  
  
def self.find_practice_exam(lang,exam_type)
 # logger.info("Lang=#{lang}")
 
   self.find_by_number_and_lang_and_exam_type(0, lang,exam_type)
  #4 self.where(number: 0, lang: lang, exam_type: exam_type)
end  

end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  # GET /examinations
  # GET /examinations.xml
 before_filter :fetch_lang ,:only => [:index, :show]
 before_action :admin?, :only => [:new, :edit, :create, :update, :destroy, :list]
  
  def index
   # @examinations = Examination.find(:all,:order =>'number')
  lang = session[:lang] 
   #I18n.locale = lang
   logger.info("**** Lang is #{I18n.locale}")
   exam_type = session[:exam_type]
 #4  @examinations = Examination.find_all_by_lang_and_exam_type(lang,exam_type, :order =>'number')
    @examinations = Examination.where(lang: lang , exam_type: exam_type).order('number')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @examinations }
    end
  end

  # GET /examinations/1
  # GET /examinations/1.xml
  def show
    @examination = Examination.find(params[:id])
   #4 @chapters =@examination.chapters.find(:all,:order=>'ind')  
   @chapters =@examination.chapters.order('ind')  
 end

  # GET /examinations/new
  # GET /examinations/new.xml
  def new
    @examination = Examination.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @examination }
    end
  end

  # GET /examinations/1/edit
  def edit
    @examination = Examination.find(params[:id])
  end

  # POST /examinations
  # POST /examinations.xml
  def create
    @examination = Examination.new(examination_params)
    @examination.number = Examination.count+1
    respond_to do |format|
      if @examination.save
        flash[:notice] = 'Examination was successfully created.'
        format.html { redirect_to(list_examinations_url)  }
        format.xml  { render :xml => @examination, :status => :created, :location => @examination }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @examination.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /examinations/1
  # PUT /examinations/1.xml
  def update
    @examination = Examination.find(params[:id])

    respond_to do |format|
      if @examination.update(examination_params)
	  #4 if @examination.update_attributes(params[:examination])
        flash[:notice] = 'Examination was successfully updated.'
        format.html { redirect_to(list_examinations_url)  }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @examination.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /examinations/1
  # DELETE /examinations/1.xml
  def destroy
    @examination = Examination.find(params[:id])
    @examination.destroy

    respond_to do |format|
      format.html { redirect_to(list_examinations_url) }
      format.xml  { head :ok }
    end
  end
  
  
  def list
     @examinations = Examination.all.order(:number)
	    render layout: 'list'

  end


def instructions
   @exam = Examination.find(params[:id].to_i)
    session[:lang] = @exam.lang   #save the date in session for index to select only the relevant exams
    session[:exam_type] = @exam.exam_type
   render :action => "instructions_#{@exam.lang}_#{@exam.exam_type}"
end  
  
def exam_choice
  lang = params[:lang] || "hebrew"
 
  @psycho_exam = Examination.find_practice_exam(lang,"psycho")
  @amir_exam =  Examination.find_practice_exam(lang,"amir")
  @yael_exam =  Examination.find_practice_exam(lang,"yael")
  @engchaps_exam =  Examination.find_practice_exam(lang,"engchaps")
 
  render :action => "exam_choice_#{lang}"  
end
  

def fetch_lang
   I18n.locale  = session[:lang] 
end   
  
def examination_params
   params.require(:examination).permit(:name, :instruction, :lang, :exam_type,:number)

end 

end

app/helpers/examinations_helper.rb
module ExaminationsHelper




end

app/views/examinations/Copy of index.html.erb
<h1>Listing examinations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
  </tr>

<% for examination in @examinations %>
  <tr>
    <td><%=h examination.name %></td>
    <td><%=h examination.number %></td>
    <td><%= link_to 'Show', examination %></td>
    <td><%= link_to 'Edit', edit_examination_path(examination) %></td>
    <td><%= link_to 'Destroy', examination, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New examination', new_examination_path %>

app/views/examinations/Copy of show.html.erb
<body dir=rtl>
<center>
<% if !@chapter %>
<h2>נא לבחור פרק ב<%=@examination.name%></h2>
<% else %>
<h2> פרק מס  <%=@chapter.ind%> ( <%=@chapter.name%> ) </h2>
<% end %>
<table width=400 dir=rtl >
<tr>
<% for chapter in @chapters %>
<td>
<%= link_to "<B>פרק מספר: " + chapter.ind.to_s, {:controller => :items, :action=>:index, :id=>chapter} %> </td>
<% end %>
</tr>
</table>



app/views/examinations/_item.html.erb
<tr style="display:none" bgcolor=#fadefa id='<%=ind%>'>
<% chapter_number=item.chapter.number %>
<%=player_for( chapter_number, item.instructions,'הוראות', '#2AAAFF' )%>
<%=player_for( chapter_number, item.text1, 'פסקה ראשונה', '#7FFF7F' )%>  
<%=player_for( chapter_number, item.text2, 'פסקה שנייה', '#7FFF7F' )%>  
<%=player_for( chapter_number, item.text3, 'פסקה שלישית', '#7FFF7F' )%>
<%=player_for( chapter_number, item.text4, 'פסקה רביעית', '#7FFF7F' )%>
<%=player_for( chapter_number, item.text5, 'פסקה חמישית', '#7FFF7F' )%>
<%=player_for( chapter_number, item.question ,'שאלה' ,'#F9F085')%>
<%=player_for( chapter_number, item.answer1, 'תשובה 1', '#ABD3C0' )%>
<%=player_for( chapter_number, item.answer2, 'תשובה 2', '#ABD3C0' )%>
<%=player_for( chapter_number, item.answer3, 'תשובה 3', '#ABD3C0' )%>
<%=player_for( chapter_number, item.answer4, 'תשובה 4', '#ABD3C0' )%>
</tr>


app/views/examinations/edit.html.erb
<h1>Editing examination</h1>

<%= form_for(@examination) do |f| %>
   <% if @examination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@examination.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @examination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
   <p> 
    <%= f.label :number %>  <br />  
	  צריך להיות 0 בבחינה שהיא תרגול  <br />
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  
   <p>
    <%= f.label :instruction %><br />
    <%= f.text_field :instruction %>
  </p>
   <p>
    <%= f.label :lang %><br />
    <%= select("examination", "lang",[["עברית","hebrew"],["ערבית","arabic"] ] , 
                         { :include_blank => false }) %>
   </p>
    <p>
    <%= f.label :exam_type %><br />
    <%= select("examination", "exam_type",[["פסיכומטרי","psycho"],["אמיר","amir"],["ידע עברית","yael"],["פרקי אנגלית","engchaps"]] , 
                         { :include_blank => false }) %>
   </p>
  <p>
       <%= submit_tag 'submit'  %>
  </p>
<% end %>

<%= link_to 'Back', list_examinations_path %>

app/views/examinations/exam_choice_hebrew.html.erb
<div id="inst">
<center>


<title>מערכת השמעה לבחינה מוקלטת </title>
<H2>מערכת השמעה לבחינה מוקלטת </H2>
</center>


לפניך הדגמה של מערכת השמעת בחינה המיועדת לנבחנים עיוורים או כבדי ראיה.</br>

המערכת פותחה במרכז הארצי לבחינות ולהערכה.</br>

מטרת מערכת זו הינה לאפשר לנבחנים שאושר להם תנאי זה (השמעת הבחינה המוקלטת) להכיר את התהליך, וכך לתפקד באופן יעיל יותר בבחינה.</br>

הפעלת המערכת נעשית באמצעות העכבר.</br>

באפשרותך לבחור את קצב השמעת הטקסט, ולבחור את גודל האותיות על המסך על ידי לחיצה על אייקונים הנמצאים בחלקו העליון של המסך.</br>
נבחנים עיוורים ייעזרו בעת הבחינה בבוחן שישמיע את הבחינה ויסמן את תשובותיהם לפי הוראותיהם.</br>
 נבחנים כבדי ראיה יוכלו להפעיל את המערכת באופן עצמאי או להיעזר בבוחן - לפי בחירתם.</br>


 </br></br></br>
<center>

<%= link_to "בחינה פסיכומטרית",instructions_examination_url(@psycho_exam),:class=>"link_to_exams" %> &nbsp; 
<%= link_to "אמי\"ר",instructions_examination_url(@amir_exam),:class=>"link_to_exams" %> &nbsp;
<%= link_to "ידע עברית",instructions_examination_url(@yael_exam),:class=>"link_to_exams" %> &nbsp;
<%= link_to "פרקי אנגלית",instructions_examination_url(@engchaps_exam),:class=>"link_to_exams" %> &nbsp; 

</center>
</div>
<BR><BR>
 

app/views/examinations/index.html.erb
<center>
<h1><center><%= t('examinations.title') -%></h1>
<table height=500 dir=rtl align=center>
<% for examination in @examinations %>
  <tr>
    <td class='main'> 
    <% if examination.number ==0 %>
          <%=link_to t('examinations.back_to_tirgul'),examination_url(examination) %>
     <%else%>
           <%=link_to t('examinations.start'),examination_url(examination) %>
     <%end%>
    </td>

  </tr>
<% end %>
</table>
</center>

app/views/examinations/instructions_arabic_amir.html.erb
<div id="inst">
<center>
<H2>نظام صوتيّ لإسماع امتحان "أمير" مُسجَّل - شاشة شروح </H2>
</center>
<BR>  
<BR>  أمامك تعليمات لتشغيل نظام الإسماع.
<BR>  يشتمل نظام الإسماع على امتحان تمرينيّ يسبق الامتحان الحقيقيّ.
<BR>  في بداية التّمرين يجب الاستماع إلى التعليمات العامّة للامتحان. بعدئذٍ يجب الانتقال إلى فصل التّمرين. 
<BR>  الدّخول إلى فصل التّمرين (أو لكلّ سؤال لاحقًا) يتمّ بواسطة الضّغط على الزّر الأيسر في الفأرة حينما يكون المؤشّر موجودًا على الأيقونة (Icon) الملائمة.
<BR>  بعد انتهائك من التّمرين يمكنك البدء بالامتحان الحقيقيّ.

<BR>  ترتيب الفصول في الامتحان حُدِّدَ مسبقًا ويجب التقدُّم بموجبه.

<BR>  داخل كلّ فصل، تظهر الأسئلة بحسب ترتيب معيّن لكن يمكن اختيار سماعها حسب التّرتيب الّذي ترغب به.

<BR>  الضّغط بالفأرة على سؤال ما يعرض إمكانيّات إسماعه: إسماع متواصل للسّؤال مع إمكانيات الإجابة، أو إسماع منفصل للسّؤال ولكلّ واحدة من إمكانيّات الإجابة.

<BR>  في قِطع فهم المقروء توجد إمكانيّة إسماع النّصّ بأكمله، وإمكانيّة إسماع كلّ فقرة من فقراته على حدة.

<BR>  لدى إسماع أي جزء من الامتحان، يمكن إيقاف الإسماع بواسطة الضّغط على الشّارة الملائمة، ويمكن تجديد الإسماع من ذات الموقع بواسطة الضّغط مرّة أخرى على ذات الشّارة.

<BR>  إذا كان إسماع قسم ما لم ينتهِ بعد، فإنّ الضّغط على قسم آخر سيوقف الإسماع فورًا وسيؤدّي إلى إسماع القسم الآخر.

<BR>  

</p>    
<BR>  

<BR><BR>
<center>
<%= link_to "لبدء التّمرّن לתחילת התרגול",examination_url(@exam),:class=>"link_to_exams" %>
</center>
<BR><BR>

app/views/examinations/instructions_arabic_yael.html.erb
<div id="inst">
<center>
<H2>نظام صوتيّ لإسماع امتحان معرفة العبريّة  مُسجَّل - شاشة شروح </H2>
</center>
<BR>  
<BR>  أمامك تعليمات لتشغيل نظام الإسماع.
<BR>  يشتمل نظام الإسماع على امتحان تمرينيّ يسبق الامتحان الحقيقيّ.
<BR>  في بداية التّمرين يجب الاستماع إلى التعليمات العامّة للامتحان. بعدئذٍ يجب الانتقال إلى فصل التّمرين. 
<BR>  الدّخول إلى فصل التّمرين (أو لكلّ سؤال لاحقًا) يتمّ بواسطة الضّغط على الزّر الأيسر في الفأرة حينما يكون المؤشّر موجودًا على الأيقونة (Icon) الملائمة.
<BR>  بعد انتهائك من التّمرين يمكنك البدء بالامتحان الحقيقيّ.

<BR>  ترتيب الفصول في الامتحان حُدِّدَ مسبقًا ويجب التقدُّم بموجبه.

<BR>  داخل كلّ فصل، تظهر الأسئلة بحسب ترتيب معيّن لكن يمكن اختيار سماعها حسب التّرتيب الّذي ترغب به.

<BR>  الضّغط بالفأرة على سؤال ما يعرض إمكانيّات إسماعه: إسماع متواصل للسّؤال مع إمكانيات الإجابة، أو إسماع منفصل للسّؤال ولكلّ واحدة من إمكانيّات الإجابة.

<BR>  في قِطع فهم المقروء توجد إمكانيّة إسماع النّصّ بأكمله، وإمكانيّة إسماع كلّ فقرة من فقراته على حدة.

<BR>  لدى إسماع أي جزء من الامتحان، يمكن إيقاف الإسماع بواسطة الضّغط على الشّارة الملائمة، ويمكن تجديد الإسماع من ذات الموقع بواسطة الضّغط مرّة أخرى على ذات الشّارة.

<BR>  إذا كان إسماع قسم ما لم ينتهِ بعد، فإنّ الضّغط على قسم آخر سيوقف الإسماع فورًا وسيؤدّي إلى إسماع القسم الآخر.

<BR>  

</p>    
<BR>  

<BR><BR>
<center>
<%= link_to "لبدء التّمرّن לתחילת התרגול",examination_url(@exam),:class=>"link_to_exams" %>
</center>
<BR><BR>

app/views/examinations/instructions_hebrew_amir.html.erb
<div id="inst">
<center>
<H2>מערכת השמעה לבחינת אמי"ר מוקלטת - מסך הסבר</H2>
</center>
לפניך הוראות לתפעול מערכת ההשמעה.<BR>
מערכת ההשמעה כוללת בחינה לתרגול הקודמת לבחינה האמיתית.<BR>
בתחילת התרגול יש לשמוע את ההוראות הכלליות של הבחינה. לאחר מכן יש לעבור לפרק התרגול. <BR>
הכניסה לפרק התרגול (או לכל שאלה בהמשך) נעשית על ידי לחיצה שמאלית על העכבר כאשר הסמן נמצא על האייקון המתאים.<BR>
בתום התרגול תוכל להתחיל את הבחינה האמיתית.<BR>

סדר הפרקים בבחינה קבוע מראש ויש להתקדם על פיו.<BR>

בתוך כל פרק אפשר לבחור בסדר ההשמעה הרצוי, בין סוגי השאלות השונים.<BR>

לחיצת העכבר על שאלה תציג את אפשרויות ההשמעה שלה: השמעה רציפה של השאלה ואפשרויות התשובה,  או השמעה נפרדת של השאלה וכל אחת מאפשרויות התשובה.<BR>


בקטעי הבנת טקסט קיימת אפשרות להשמעה רציפה של הקטע כולו, ואפשרות להשמעה של כל אחת מהפסקאות בנפרד.<BR>

במהלך ההשמעה של חלק כלשהו אפשר לעצור את ההשמעה על ידי לחיצה על הסימן המתאים, ואפשר לחדש את ההשמעה מאותו מקום על ידי לחיצה נוספת על אותו סימן.<BR>

לחיצה על חלק אחד תפסיק אוטומטית את ההשמעה ותביא להשמעת החלק האחר.<BR>

<BR><BR>
<center>
<%= link_to "לתחילת התרגול",examination_url(@exam),:class=>"link_to_exams" %> &nbsp;

</center>
</div>
<BR><BR>

app/views/examinations/instructions_hebrew_engchaps.html.erb
<div id="inst">
<center>
<H2>מערכת השמעה לבחינת "פרקי אנגלית" מוקלטת - מסך הסבר</H2>
</center>
לפניך הוראות לתפעול מערכת ההשמעה.<BR>
מערכת ההשמעה כוללת בחינה לתרגול הקודמת לבחינה האמיתית.<BR>
בתחילת התרגול יש לשמוע את ההוראות הכלליות של הבחינה. לאחר מכן יש לעבור לפרק התרגול. <BR>
הכניסה לפרק התרגול (או לכל שאלה בהמשך) נעשית על ידי לחיצה שמאלית על העכבר כאשר הסמן נמצא על האייקון המתאים.<BR>
בתום התרגול תוכל להתחיל את הבחינה האמיתית.<BR>

סדר הפרקים בבחינה קבוע מראש ויש להתקדם על פיו.<BR>

בתוך כל פרק אפשר לבחור בסדר ההשמעה הרצוי, בין סוגי השאלות השונים.<BR>

לחיצת העכבר על שאלה תציג את אפשרויות ההשמעה שלה: השמעה רציפה של השאלה ואפשרויות התשובה,  או השמעה נפרדת של השאלה וכל אחת מאפשרויות התשובה.<BR>


בקטעי הבנת טקסט קיימת אפשרות להשמעה רציפה של הקטע כולו, ואפשרות להשמעה של כל אחת מהפסקאות בנפרד.<BR>

במהלך ההשמעה של חלק כלשהו אפשר לעצור את ההשמעה על ידי לחיצה על הסימן המתאים, ואפשר לחדש את ההשמעה מאותו מקום על ידי לחיצה נוספת על אותו סימן.<BR>

לחיצה על חלק אחד תפסיק אוטומטית את ההשמעה ותביא להשמעת החלק האחר.<BR>

<BR><BR>
<center>
<%= link_to "לתחילת התרגול",examination_url(@exam),:id=>"link_to_exams" %> &nbsp;

</center>
</div>
<BR><BR>

app/views/examinations/instructions_hebrew_psycho.html.erb
<div id="inst">
<center>
<H2>מערכת השמעה לבחינה פסיכומטרית מוקלטת - מסך הסבר</H2>
</center>

<BR>
לפניך הוראות לתפעול מערכת ההשמעה.<BR>
מערכת ההשמעה כוללת בחינה לתרגול הקודמת לבחינה האמיתית.<BR>
בתחילת התרגול יש לשמוע את ההוראות הכלליות של הבחינה. לאחר מכן יש לעבור לפרקי התרגול. פרקי התרגול מקבילים לפרקים הקיימים בבחינה האמיתית. 
הכניסה לפרק התרגול (או לכל שאלה בהמשך) נעשית על ידי לחיצה שמאלית על העכבר כאשר הסמן נמצא על האייקון המתאים.<BR>
בתום התרגול תוכל להתחיל את הבחינה האמיתית.<BR>
סדר הפרקים בבחינה קבוע מראש ויש להתקדם על פיו.<BR>
בתוך כל פרק אפשר לבחור בסדר ההשמעה הרצוי, בין סוגי השאלות השונים.<BR>
לחיצת העכבר על שאלה תציג את אפשרויות ההשמעה שלה: השמעה רציפה של השאלה ואפשרויות התשובה,  או השמעה נפרדת של השאלה וכל אחת מאפשרויות התשובה.<BR>
בקטעי הבנת טקסט קיימת אפשרות להשמעה רציפה של הקטע כולו, ואפשרות להשמעה של כל אחת מהפסקאות בנפרד.<BR>
במהלך ההשמעה של חלק כלשהו אפשר לעצור את ההשמעה על ידי לחיצה על הסימן המתאים, ואפשר לחדש את ההשמעה מאותו מקום על ידי לחיצה נוספת על אותו סימן.<BR>
לחיצה על חלק אחד תפסיק אוטומטית את ההשמעה ותביא להשמעת החלק האחר.<BR>
בפרק החשיבה הכמותית, נוסף על השמעת ההוראות והשאלות אפשר להשמיע גם את הנוסחאות במתמטיקה, על ידי לחיצה ימנית של העכבר על שם הנוסחה הרצויה.<BR>
הנוסחאות מופיעות בצידו השמאלי של המסך.<BR>


<BR><BR>
<center>
<%= link_to "לתחילת התרגול",examination_url(@exam),:class=>"link_to_exams" %> &nbsp;

</center>
</div>
<BR><BR>

app/views/examinations/instructions_hebrew_yael.html.erb
<div id="inst">
<center>
<H2>מערכת השמעה לבחינת יע"ל מוקלטת - מסך הסבר</H2>
</center>
לפניך הוראות לתפעול מערכת ההשמעה.<BR>
מערכת ההשמעה כוללת בחינה לתרגול הקודמת לבחינה האמיתית.<BR>
בתחילת התרגול יש לשמוע את ההוראות הכלליות של הבחינה. לאחר מכן יש לעבור לפרק התרגול. <BR>
הכניסה לפרק התרגול (או לכל שאלה בהמשך) נעשית על ידי לחיצה שמאלית על העכבר כאשר הסמן נמצא על האייקון המתאים.<BR>
בתום התרגול תוכל להתחיל את הבחינה האמיתית.<BR>

סדר הפרקים בבחינה קבוע מראש ויש להתקדם על פיו.<BR>

בתוך כל פרק אפשר לבחור בסדר ההשמעה הרצוי, בין סוגי השאלות השונים.<BR>

לחיצת העכבר על שאלה תציג את אפשרויות ההשמעה שלה: השמעה רציפה של השאלה ואפשרויות התשובה,  או השמעה נפרדת של השאלה וכל אחת מאפשרויות התשובה.<BR>


בקטעי הבנת טקסט קיימת אפשרות להשמעה רציפה של הקטע כולו, ואפשרות להשמעה של כל אחת מהפסקאות בנפרד.<BR>

במהלך ההשמעה של חלק כלשהו אפשר לעצור את ההשמעה על ידי לחיצה על הסימן המתאים, ואפשר לחדש את ההשמעה מאותו מקום על ידי לחיצה נוספת על אותו סימן.<BR>

לחיצה על חלק אחד תפסיק אוטומטית את ההשמעה ותביא להשמעת החלק האחר.<BR>

<BR><BR>
<center>
<%= link_to "לתחילת התרגול",examination_url(@exam),:id=>"link_to_exams" %> &nbsp;

</center>
</div>
<BR><BR>

app/views/examinations/new.html.erb
<h1>מבחן חדש</h1>

<%= form_for(@examination) do |f| %>
 
   <% if @examination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@examination.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @examination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :instruction %><br />
    <%= f.text_field :instruction %>
  </p>
   <p>
    <%= f.label :lang %><br />
    <%= select("examination","lang",[["עברית","hebrew"],["ערבית","arabic"]],{ :include_blank => false} ) %>
  </p>
   <p>
    <%= f.label :exam_type %><br />
    <%= select("examination","exam_type",[["פסיכומטרי","psycho"],["אמיר","amir"],["ידע עברית","yael"],["פרקי אנגלית","engchaps"]],{ :include_blank => true} ) %>
  </p>
  <p>
    <%= f.submit "לשמור" %>
  </p>
<% end %>

<%= link_to 'לרשימת המבחנים', list_examinations_path %>

app/views/examinations/show.html.erb
<center>

<% if @examination.number != 0 %>
   <h2><%=t('examinations.listen_inst2') %></h2>
<% else %>
   <h2><%=t('examinations.listen_inst') %></h2>
<% end %>

<table>
<tr>
   <%= raw player_for_3("general","9", @examination.instruction,t('examinations.inst_gen'),'yellow') if @examination.instruction %>
</tr>
</table>

<hr>

<% if !@chapter %>
  <h2><%=t('items.start') %>  <%= link_to @examination.name.html_safe , chapter_items_url(@chapters[0], :examination_id => @examination.id) %> 
  </h2>    
  <% if @examination.number != 0 %>
        <h2><%=t('examinations.start_time').html_safe %></h2>
   <% end %>

<% else %>

   <h2> <%=t('items.chapter') %>  <%=@chapter.ind%> ( <%=@chapter.name%> ) </h2>
<% end %>



<br>

</center>